### ISSUE TITLE
\pdffilesize doesn't work correctly in eptex and perhaps other engines

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#1121]
In the last months I have seen rather regularly question of miktex users where the format creation failed due to some problem with UnicodeData.txt. The reason was unclear. Looking at https://tex.stackexchange.com/q/649555/2388 (which lead to issue #1120) I could actually reproduce the failure for once with eptex and so took a look. 

I get a reproducible failure in eptex (I added it to the latex code and then tried to create a format) for 

~~~~
\newcount\mycnt \mycnt=\pdffilesize{file.txt}  
~~~~

With the error 

~~~~
! Missing number, treated as zero.
<to be read again>
                   \BAD.
~~~~

as soon as `file.txt` contains more than 9 character. If it contains only XXXXXXXXX there is no problem.

**Comment by edocevoli** [comment]
Thank you. `\pdffilesize` has a special implementation for xetex and ptex. So I think that the bug only affects these two engines.

**Comment by u-fischer** [comment]
I saw once a question with pdflatex too: https://tex.stackexchange.com/q/592762/2388.  And this issue used pdftex too https://github.com/MiKTeX/miktex/issues/959. 
But there I have no problems. I can only reproduce it with eptex.

**Comment by ostaith** [comment]
i build this [project](https://github.com/Steve-Cheung-emct/upLaTeX-SZ.CLS) also have similar error (sorry it's complex, i don't know how to produce MWE), please check whether it is same problem or not:

```
Package pxjahyper Warning: Option 'otfcid'/'otfmacros' is disabled, because
(pxjahyper)                package 'bxjatoucs' is unavailable.

(D:\MiKTeX\tex/latex/pxjahyper\pxjahyper-uni.def))
(D:\MiKTeX\tex/latex/bookmark\bookmark.sty
(D:\MiKTeX\tex/latex/bookmark\bkm-dvipdfm.def))
(D:\MiKTeX\tex/latex/silence\silence.sty))
No file main.aux.
《縦組モード》 [1] [2]
No file main.toc.
[3] [4]
! Missing number, treated as zero.
<to be read again>
                   1BAD.
l.70 \input{TESTTEXT/testtext}

?
```

but if i change this line `\input{TESTTEXT/testtext}` to `\input{TESTTEXT/testtext.tex}` (add `.tex` suffix), the error disappear.

**Comment by edocevoli** [comment]
It turns out that this is due to a buffer overflow in `texmfmp.c`. A buffer with a capacity of 20 bytes is reserved. pTeX characters have a width of two bytes. So the buffer overrun occurs if the string is longer than 9 characters (+ null-byte). This is not MiKTeX-specific. But the effect of the buffer overrun may depend on the C/C++ compiler.

For future reference (when notifying pTeX maintainers), here is the code which causes the buffer overrun:

https://github.com/TeX-Live/texlive-source/blob/76328dde471072aa5a52d880a92f58c22352349c/texk/web2c/lib/texmfmp.c#L3569-L3611
