### ISSUE TITLE
MiKTeX Console throws "Peer certificate cannot be authenticated with given CA certificates" during "check for updates" or "update packages" run

### ISSUE THREAD

**Issue by king-h** [MiKTeX/miktex#118]
Both versions of MiKTeX Console:
- basic-miktex-2.9.6643.exe
- basic-miktex-2.9.6643-x64.exe

allow no proper internet connection to:
- update packages 
- check for updates

We always get the following error message: "**Peer certificate cannot be authenticated with given CA certificates**" although the application is not located behind a proxy or a firewall.

The configuration of MiKTeX is set to:
- Install from "a random package repository on the Internet"

Any hints to get rid of this issue? Is there a root certificate of the randomly selected package repository missing in the keystore of MikTeX? Where is this keystore?

**Comment by edocevoli** [comment]
Seems you have installed software which tries to inspect the SSL traffic. This software can be: malware, security software. You should identify this software and take further steps.

**Comment by king-h** [comment]
@edocevoli: "Symantec Endpoint Protection" is running here on a managed workstation. We assume it prevents MiKTeX from connecting to the remote package repositories. When disabling "Symantec Endpoint Protection" (including its embedded Firewall) the error stays the same. 

Seems to be that MiKTeX console is not compatible with "Symantec Endpoint Protection". All other software running on this workstations works expect MiKTeK.

As even USB access is prevent - due to the fact that it's a managed workstation, we cannot copy a package repository to this system via a USB stick.

What would you suggest to get rid of the problem?

**Comment by hrrichardson** [comment]
king-h did you find a solution to this issue? i am getting the same error from my install as well

**Comment by edocevoli** [comment]
A possible workaround for this issue: select a non-HTTPS repository. This can be achieved on the command-line with [mpm(1)](https://docs.miktex.org/manual/mpm.html).

**Comment by joe425** [comment]
I am having the same problem when installing packages. Also when I access the https://miktex.org website I get a certificate error: "The certificate can not be verified up to a verified certificate authority"

From reading about letsencrypt certificates: I have the "DST Root CA X3" certificate that should verify the letsencrypt certificate. But for some reason this is not working. The certification path is show as: 
ISRG Root X1 -->Lets Encrypt Authority X3 --> miktex.org

The "DST Root CA X3" certificate is not mentioned?

**Comment by edocevoli** [comment]
The certification path looks okay.

ISRG Root X1 must be installed in the certificate store. On my  Windows 10 machine:

![capture](https://user-images.githubusercontent.com/20090840/44783758-a4e3da80-ab8b-11e8-8dd8-cb774897861f.PNG)

**Comment by hrrichardson** [comment]
thanks for the tip edocevoli, 

joe425 - with the tip from edocevoli i was able to fix this issue by going to https://letsencrypt.org/certificates/ to find the link to the ISRG ROOT X1 certificate, i saved the text as a .crt file. 

since i am working on (fighting with) a windows machine i used MMC (microsoft management console) to add the root certificate my "trusted root authority"

i then uninstalled and reinstalled miktex (since i had been messing with settings on the previous install) and by some dark magic it is now able to install updates from an internet repository.

**Comment by joe425** [comment]
From https://letsencrypt.org/certificates/
"Our intermediate is signed by ISRG Root X1. However, since we are a very new certificate authority, ISRG Root X1 is not yet trusted in most browsers. In order to be broadly trusted right away, our intermediate is also cross-signed by another certificate authority, IdenTrust, whose root is already trusted in all major browsers. Specifically, IdenTrust has cross-signed our intermediate using their DST Root CA X3."

I have the DST Root CA X3 certificate installed so would expect it to work without manually adding ISRG Root X1 certificate. Will have to ask the IT dept if this ok to add ISRG Root X1.

**Comment by mnordhoff** [comment]
Microsoft added ISRG Root X1 recently. https://letsencrypt.org/2018/08/06/trusted-by-all-major-root-programs.html I don't know how Windows works, but there might be an update available soon, or already available but your IT department is blocking it.

**Comment by BeerStud** [comment]
You might peruse these three URLs for further information on updating the certificates on your machine. It differs slightly between Windows versions. The regular Windows Update should do it automatically though.

**Comment by Courvoisier13** [comment]
Hi all,

Is this a new issue that everyone started having. I am on a work machine, that has Symantec EP. I also have a proxy. The miktex package manager was working fine, to install a package I used identification - put the username and pwd and it worked (I can confirm that on July 16 2018, it was working). Then on Sept 11 2018 it stopped.

Today, I tried installing the certificates in my personal certs, I added HTTP_PROXY and HTTPS_PROXY with the full proxy +username/pwd, I used mpm from cmd with 
`mpm --repository=http://distrib-coffee.ipsl.jussieu.fr/ --verbose --update-db` but nothing seems to work. I keep getting the following in the log:

```
2018-09-17 10:46:01,141+0100 INFO  mpmcli - starting: mpmcli 2.9.6727 (MiKTeX 2.9.6745 64-bit)
2018-09-17 10:46:01,141+0100 INFO  mpmcli - Operating on the private (per-user) MiKTeX setup
2018-09-17 10:46:01,348+0100 FATAL mpmcli - Failure when receiving data from the peer
2018-09-17 10:46:01,348+0100 FATAL mpmcli - Info: 
2018-09-17 10:46:01,348+0100 FATAL mpmcli - Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp
2018-09-17 10:46:01,348+0100 FATAL mpmcli - Line: 357
```
and when I open the miktex console app, it keeps saying Install from = a random package repo on the internet. and not http://distrib-coffee.ipsl.jussieu.fr/

What did you do other to get it to work?

**Comment by roymmammen** [comment]
Hi,

Even after changing the repository to a non SSL site by running "mpm --set-repository=http://ctan.math.illinois.edu/ --admin", I am still getting the following error while trying to install a package. 

I can see from the console (under Setting and Packages tab) that the upstream url (where the packages are installed from) has successfully changed. However, I am not sure why the package install is  still complains about SSL cert. 

Is there a work around to this issue?

Peer certificate cannot be authenticated with given CA certificates

More info: https://miktex.org/kb/fix-ssl-cacert

Thanks

**Comment by jmartins25** [comment]
Hi, 

I am having the same problem and I do not know how to solve it. 

It keeps saying 

"Peer certificate cannot be authenticated with given CA certificates

More info: https://miktex.org/kb/fix-ssl-cacert "

code="60"

Can someone help me. Thanks.

**Comment by Sujay-Bhatt** [comment]
> 
> 
> Hi,
> 
> I am having the same problem and I do not know how to solve it.
> 
> It keeps saying
> 
> "Peer certificate cannot be authenticated with given CA certificates
> 
> More info: https://miktex.org/kb/fix-ssl-cacert "
> 
> code="60"
> 
> Can someone help me. Thanks.

hrrichardson's solution worked for me: "Fix this issue by going to https://letsencrypt.org/certificates/ to find the link to the ISRG ROOT X1 certificate, i saved the text as a .crt file.

since i am working on (fighting with) a windows machine i used MMC (microsoft management console) to add the root certificate my "trusted root authority""..

For a Windows 7 machine:
0. Install MiKteX 2.9
1. Copy the contents from ISRG Root X1 (self-signed)  at https://letsencrypt.org/certificates/ 
2. Open a notepad paste the contents. Save as ISRG Root X1.crt
3. Start > mmc
4. File > Add Snap-in > Cerificates-current user (add this and save)
5. Right-click Trusted Root Cerificates > All Tasks > Import
6. Import the ISRG Root X1.crt file and install.
7. Reopen MiKteX, everything else show work normal. The console prompts to choose and install packages.

Good luck.

**Comment by Cory-Kramer** [comment]
I am having the same issue as the above comments. None of the above workarounds fixes the issue for me.

**Comment by meccs76** [comment]
The Chain of Thrust is broken somewhere. Installing the DST Root CA X3 as thrusted rot cert and, if this dos not work, also installing the miktex.org server cert as thrusted publisher did the job for me.

**Comment by sw549** [comment]
Thanks edocevoli  and hrrichardson.

My Miktex package is updating properly following hrrichardson's suggestion. I saved the  ISRG ROOT X1 as .crt file then imported it into the Trusted Root Certificates using mmc using the instructions here:
http://www.sqlservermart.com/HowTo/Windows_Import_Certificate.aspx

After this, the updates are working properly.

> thanks for the tip edocevoli,
> 
> joe425 - with the tip from edocevoli i was able to fix this issue by going to https://letsencrypt.org/certificates/ to find the link to the ISRG ROOT X1 certificate, i saved the text as a .crt file.
> 
> since i am working on (fighting with) a windows machine i used MMC (microsoft management console) to add the root certificate my "trusted root authority"
> 
> i then uninstalled and reinstalled miktex (since i had been messing with settings on the previous install) and by some dark magic it is now able to install updates from an internet repository.

**Comment by schoenbub** [comment]
Hi there, 
I am having the same issue. My OS is Windows 10 and I do not have admin rights on this computer. Following the above suggestions, I have installed the certificates (miktex.org, ISRG ROOT X1) and they show up under trusted root certificate authorities. After re-installing basic-miktex-2.9.6942-x64.exe, I still get the famous error message when I try to update:

ERROR DETAILS
Program: C:\Users\myname\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:264
Error: Peer certificate cannot be authenticated with given CA certificates
Details: 
  code: 60
  url: https://api2.miktex.org/hello

The same error message also appears when I try to change the setting for the remote repository. Is there a way to specify the remote repository during installation - may this help to resolve the issue? Otherwise, how could I find out where the chain of trust is broken? Or will future MikTex updates resolve this issue and I should wait until then?

Thank you for your help

**Comment by senf-mb** [comment]
Hi,
I have the same certification problem on my win10 machine. I already tried all the mentioned paths so solve the problem and when I checked my chain of trust with sslshopper.com it tells me that everything should be alright when I try to reach https://api2.miktex.org/hello. Is this the url miktex is trying to connect to do updates and to download new packages?

I have no proxy, I'm running miktex 2.9.7429. Is there anything I might have forgotten to check?

**Comment by senf-mb** [comment]
For all win10 users with this error... I had this issue because somehow miktex needs IE11 to get the right CA Certificates. I don't know why but on several win7 stations it worked without IE but on my win 10 it just worked when IE11 is installed and you use the IE to install the certificates with the wizard. At first I installed them manually to both Local Machine and Currend User; there was no change. Then I installed them with the wizard to both (LM and CU) nothing changed. When I reinstalled IE, I tried to connect to severals websites (including Google) and there where multiple CA Cert issues (also on Google). When I installed the certificates with the IE wizard and reinstalled Miktex, the CA Cert error was gone. I don't know why it NEEDS IE but maybe this could be changed!

**Comment by mrwunderbar666** [comment]
Got the error today on Ubuntu 20.04:

```
**GENERAL MIKTEX INFORMATION
ReportDate: 2021-09-24 15:17:41
CurrentVersion: 21.6
SetupDate: 2021-09-17 10:25:00
SetupVersion: 21.6
Configuration: Regular
GitInfo: 1dd0ae5 / 2021-06-06 11:29:06
OS: Linux 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64
SharedSetup: yes
LinkTargetDirectory: /usr/local/bin
PathOkay: yes
LastUpdateCheckAdmin: 2021-09-17 11:33:46
LastUpdateAdmin: 2021-09-17 10:26:27
LastUpdateDbAdmin: 2021-09-17 11:33:46
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: /var/lib/miktex-texmf
Root1: /var/cache/miktex-texmf
Root2: /usr/local/share/miktex-texmf
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf
Invokers: .../systemd/systemd/miktex-console-

ERROR DETAILS
Program: /usr/bin/miktex-console
Source: Libraries/MiKTeX/PackageManager/CurlWebSession.cpp:247
Error: SSL peer certificate or SSH remote key was not OK
Details: 
  url: https://api2.miktex.org/hello
  code: 60
**
```

Same error when I ping `https://api2.miktex.org/hello` with `curl`

Any ideas? It worked last week...
