### ISSUE TITLE
 MiKTeX 22.10 Portable is missing `pdflatex` when installing on subst drive

### ISSUE THREAD

**Issue by SiggyBar** [MiKTeX/miktex#1262]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

This is the same bug as reported in #1183 (opening a new issue since I cannot comment on a closed one).

`pdflatex.exe` gets installed when installing on the `C:` drive but not on the `D:` drive.

**Comment by SiggyBar** [comment]
@IlonkaP Does installing on the `C:` drive work for you?

**Comment by IlonkaP** [comment]
> @IlonkaP Does installing on the `C:` drive work for you?

@SiggyBar I haven't tested that, tbh. Didn't come to mind. I will try an see, if I can test it within a couple days.

**Comment by IlonkaP** [comment]
Hello @SiggyBar,

so I just tried it with the latest MiKTeX command-line installer from [here](https://miktex.org/download) or more precisely [here (installer with name miktexsetup-5.2.0+b8f430f-x64)](https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/miktexsetup-5.2.0+b8f430f-x64.zip).

It seems like this version is finally working for me. At least, if I try installing directly to `C:\MikTex` or `D:\MikTex` respectively.
I ran the following commands for installation on `C:`:
```
miktexsetup_standalone.exe --verbose --local-package-repository=C:\MikTex\packages\basic --package-set=basic download
miktexsetup_standalone.exe --verbose --local-package-repository=C:\MikTex\packages\basic --package-set=basic --portable=C:\MikTex\basic --use-registry=no --modify-path=no install
```
And I ran these commands for installation on `D:`:
```
C:\miktexsetup_standalone.exe --verbose --local-package-repository=D:\MikTex\packages\basic --package-set=basic download
C:\miktexsetup_standalone.exe --verbose --local-package-repository=D:\MikTex\packages\basic --package-set=basic --portable=D:\MikTex\basic --use-registry=no --modify-path=no install
```

I did not test whether the location of the `miktexsetup_standalone.exe` played any roll in that.

The results where the same (except for cache and log files of course) and `pdflatex.exe` was correctly located in `D:\MikTex\basic\texmfs\install\miktex\bin\x64\pdflatex.exe`.

I don't know if they applied further fixes in this regard since 22.10 but with 22.12 I don't seem to have issues anymore.

Hope this helps and greetings,
Ilonka

**Comment by SiggyBar** [comment]
Thank you for the follow-up, @IlonkaP.

My `D:` drive is a subst drive:
```cmd
C:\Users\sigmund>subst
D:\: => C:\work\D
```
If I install to `C:\work\D\MiKTeX`, then everything is fine, but not if I install to `D:\MiKTeX`.  `pdflatex.exe` is a hard link to `miktex-pdftex.exe`, so it seems like the installer fails to create hard links on a subst drive.  Updating the issue title to reflect this.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

We can reopen the issues if log files are available.
