### ISSUE TITLE
Flawed pdf rendering of images in 0.6.8 version of miktex-texworks editor

### ISSUE THREAD

**Issue by mhcheops8b** [MiKTeX/miktex#1389]
PDF rendering of images is flawed after upgrading from 0.6.7 to 0.6.8 version of miktex-texworks package. Somehow it seems that outlines/"shadows" are turned on.

I am attaching the renderings of the same document in 0.6.7 and 0.6.8 version. 

Best regards,
Marek Hycko
![miktex-texworks-0 6 7-pdf-rendering](https://github.com/MiKTeX/miktex/assets/15766803/447e10fc-494a-4536-aac5-6bac3bdf5f43)
![miktex-texworks-0 6 7-version-info](https://github.com/MiKTeX/miktex/assets/15766803/fd67d95b-9d10-4244-82c0-c8893a93c512)
![miktex-texworks-0 6 8-pdf-rendering](https://github.com/MiKTeX/miktex/assets/15766803/864614fc-af3e-4ea3-9287-7ff7acd9c3ab)
![miktex-texworks-0 6 8-version-info](https://github.com/MiKTeX/miktex/assets/15766803/13c93435-0e3a-4642-be01-98569d50a8bc)

**Comment by edocevoli** [comment]
Unfortunately, I could not reproduce your issue, i.e. it's impossible to provide a fix.

**Comment by mhcheops8b** [comment]
It is manifested in diagrams with lines, ovals, arrows etc. I am sending the picture on which it should be visible. Please try it directly open in texworks and zoom it, lines in it are not solid, but "dashed" - contain white dots. Vertices in graph are supposed to be black circles, but in texworks contain also some white outline. (If you compare rendering in Acrobat Reader or pdf readers in browsers.) 

Best regards,
MH
PS: I have tried clean installation 23.10 basic, deleted also Miktex directories in AppData (Local, Roamining). And rendering with 0.6.8 was still flawed. 

[U6_2n_1-eps-converted-to.pdf](https://github.com/MiKTeX/miktex/files/12893790/U6_2n_1-eps-converted-to.pdf)

**Comment by SpinHalfLight** [comment]
I am having a similar problem, as apparently are others. See for example [PDF Quality Issue in TeXworks Preview](https://tex.stackexchange.com/questions/701022/pdf-quality-issue-in-texworks-preview) on the stack exchange. In my case, the problem appears on diagonal lines rendered via tikz in TexWorks' pdf viewer. Perhaps it is just an intentional limitation of the TexWorks viewer, but the problem does not appear in any other pdf viewer I have tried so far. Simple code shows it, e.g.

\documentclass[11pt]{article}
\usepackage{tikz}
\begin{document}
\begin{figure}
\centering
  \begin{tikzpicture}
    \draw[->, blue, solid, ultra thick] (0,0)--(2.5,4.33);
    \draw[->, red, solid, ultra thick] (2.5,4.33)--(5,0);
    \draw[->, black, solid, ultra thick] (0,0)--(5,0);
   \end{tikzpicture}
\caption{Diagonal Line Rendering Issue}
\end{figure}
\end{document}

![TexWorks Rendering](https://github.com/MiKTeX/miktex/assets/153953038/cb659954-72f5-4347-95fc-1d75531f5955)

The red and blue diagonal lines show the problem. In more complex diagrams, the issue can make corrections difficult, because the graphics are so difficult to see.

Thank you for your help!!
