### ISSUE TITLE
Ugly Rendering of the output visualization of TeXworks

### ISSUE THREAD

**Issue by SSebastiano** [MiKTeX/miktex#1435]
I have installed a updated version of MikTeX but the rendering of TeXworks is ugly (see the figure)
![cU5Q3](https://github.com/MiKTeX/miktex/assets/42721614/9fafc8f2-a13f-4f7b-8433-a59ed471691e)
The pdf output instead is perfect.

Related [Rendering issue in TeXworks](https://tex.stackexchange.com/questions/697539/rendering-issue-in-texworks)

Please can you fix the problem? Thanks. 

- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by SpinHalfLight** [comment]
I have had almost the same problem for over a month (most obvious on diagonal lines in graphics), and have attempted unsuccessfully to solve it a few times. (See an earlier post on this topic: https://github.com/MiKTeX/miktex/issues/1389, including a link to others with this problem on Physics Stack Exchange.) I tried again this evening: 1) uninstalled MikTex via MikTex Console, 2) manually removed registry inputs and Windows folders not removed by the uninstaller, 3) installed latest MikTex release for Windows, ver. 0.6.8 (MikTex 23.12), 4) installed all updates at the end of the installation, 5) left all defaults in place and opened a clean Tex file as the first action taken; but TexWorks still rendered pdf graphics poorly (and some characters as well). The triangle below shows the problem. The first image is from the TexWorks pdf viewer, the second is from the same pdf opened in another viewer (SumatraPDF) on the same computer (Windows 10), so the poor quality shows up only in the TexWorks viewer.

TexWorks:
![TexWorks Rendering](https://github.com/MiKTeX/miktex/assets/153953038/96f8cf51-ed45-4105-affe-31907ac876ff)

SumatraPDF:
![image](https://github.com/MiKTeX/miktex/assets/153953038/0695c325-cca8-436a-8774-cd2b23cdc280)

About TexWorks:
![image](https://github.com/MiKTeX/miktex/assets/153953038/4d20fd07-19d0-44ce-8318-a28a52eab817)

Thank you for your help!

**Comment by edocevoli** [comment]
Sorry, I cannot fix this problem. Maybe it will fixed in a future release.

**Comment by u-fischer** [comment]
In TeXlive 2023 the rendering in the TeXworks previewer is much better. TeXlive has as TeXworks with the following version info (sorry but I can't copy the version info, so it has to be a screenshot)

![image](https://github.com/MiKTeX/miktex/assets/4047173/ca10ae42-6fb2-49cc-90ed-b56c62c19d74)

**Comment by SpinHalfLight** [comment]
Thank you edocevoli and u-fischer for your responses. After u-fischer's comment, I looked into TexLive, but I am so used to MikTex (with minor customizations, e.g. my own spell-check file), that I am reluctant to switch. I have two old installer files for MikTex, one from 2016 and one from 2020 (basic-miktex-2.9.6069.exe and basic-miktex-20.6.29-x64.exe respectively), and will try to install one of those next on my current computer. The 2016 installation runs on an older computer (updated and perhaps overwritten by the 20.6.29 installer) and does not have the PDF rendering problem. I'll try that first and post results here. My current work-around isn't bad, just inconvenient (open PDFs in SumatraPDF for correct visuals). Thank you both for your comments and for your valuable contributions to the scientific community! Best wishes...

**Comment by SSebastiano** [comment]
@SpinHalfLight @u-fischer @edocevoli I have open an issue today https://github.com/TeXworks/texworks/issues/1037. The problem yet persist. See here in TeX.SE. community: https://tex.stackexchange.com/questions/707606/ugly-rendering-of-the-output-visualization-of-texworks. My best regards.
![NtxY2](https://github.com/MiKTeX/miktex/assets/42721614/bb9614e3-abc6-4105-af41-83e837e52072)
![siBOl](https://github.com/MiKTeX/miktex/assets/42721614/0afb0ae1-032d-47e5-b8ff-6804642b6f34)

**Comment by SpinHalfLight** [comment]
Thanks again guys. As @SSebastiano points out, the problem appears robust. I am currently using an improved work-around. The problem does not appear when using a 2022 version of TeXWorks (0.6.7), held in a separate directory (C:\Program Files) from the main MiKTeX 0.6.8 installation, which is in my C:\Users\MyAccount\AppData\Local directory. I can still run updates via the 0.6.8 MiKTeX console, since it updates a different directory, as long as I leave TeXworks.exe 0.6.7 in C:\Program Files. Here are the steps I followed for the work-around (awkward as they are):

1) I removed MiKTeX and its accompanying folders, then reinstalled it from an old 2020 MiKTeX installer file. However, I suspect my results below would be the same had I used the current 0.6.8 installer (available for download) because I then ran updates from the console to update all packages (including TeXworks) to version 0.6.8. 
2) Next, I opened and processed a tex file with graphics, downloading the necessary packages on the fly, to verify the PDF rendering problem, which occurred again, as expected. 
3) I then closed TeXworks 0.6.8, leaving everything unchanged, and downloaded and installed TeXworks 0.6.7 into C:\Program Files, a separate folder from my main MiKTeX installation in C:\Users\MyAccount\AppData\Local.
4) Then I opened TeXworks.exe 0.6.7, and it apparently found my main MiKTeX installation automatically. 
5) Finally, I opened the same tex file with graphics, processed it in 0.6.7, and the PDF rendering was error-free. I have since opened and closed other graphics-laden tex files and the rendering issue does not appear as long as I'm using 0.6.7 TeXworks installed separately, in Program Files.

This is the link I used to download the windows installer for 0.6.7 TeXworks: 
https://github.com/microsoft/winget-pkgs/blob/master/manifests/t/TUG/TeXworks/0.6.7/TUG.TeXworks.installer.yaml

It is possible that downloading and installing a stand-alone 0.6.8 TeXworks.exe from TUG would also work, meaning the important element would be having TeXworks in a separate folder, not the version number, but I haven't tried that.

Thank you again for your help!

**Comment by SSebastiano** [comment]
@SpinHalfLight @u-fischer @edocevoli The pdf file generate by TeXworks is perfect. But the (DVI) windows of TeXworks given to me a bad rendering. I have open an issue also for TeXworks at the link: https://github.com/TeXworks/texworks/issues/1037.
I hope in a solution of the problem. Best regards to everyone.

**Comment by jacobgellman** [comment]
Hi @SpinHalfLight and @SSebastiano, would there be anything wrong with it if I just uninstalled MiKTeX / TeXworks 0.6.8 and reinstalled it from version 0.6.7? Are past versions available anywhere? I am having the same issues as others in the thread.

**Comment by SSebastiano** [comment]
@jacobgellman Good morning Jacob. The problem is not yet solved after the release of the version 0.6.9 (you can see my requests in https://github.com/TeXworks/texworks/issues/1056 and https://github.com/MiKTeX/miktex/issues/1520). You are only that have report my same problem and you could write to the maintainer of MikTeX, @edocevoli, or @stloeffler for TeXworks. The old versions of TeXworks are here: https://github.com/TeXworks/texworks/releases (click the window menù Assets https://github.com/TeXworks/texworks/releases/tag/release-0.6.7).

**Comment by jacobgellman** [comment]
Thank you @SSebastiano, I solved this problem by downloading version 0.6.7. Super helpful. I hope they fix this issue in the new version. It is absolutely essential to view my figures with full quality!

**Comment by stloeffler** [comment]
@jacobgellman AFAIK, all upstream releases [<https://github.com/TeXworks/texworks/releases>] should work correctly, including 0.6.9. I think the problem may be lying somewhere in the custom MiKTeX build process. But that's only speculation, of course, without having built MiKTeX from scratch on Windows myself.

**Comment by SSebastiano** [comment]
Dear @stloeffler and @jacobgellman I personally have exposed the problem several times (see the different reports for MikTeX and TeXworks) but there has been no definitive solution. I don't think I have much influence but I think you can report or reopen the closed issue very quickly.
Best regards.

Related: https://github.com/MiKTeX/miktex/issues/1520, https://github.com/TeXworks/texworks/issues/1056, https://github.com/TeXworks/texworks/issues/1037
For information: @u-fischer, @edocevoli

**Comment by jacobgellman** [comment]
Yes, @stloeffler, it was not very difficult for me to find that others are having the same issue as I was, including e.g. @SSebastiano and @SpinHalfLight in this very thread. Therefore it seems like the problem could be widespread. It is worth reopening the issue in my opinion. Thanks very much for taking the feedback.

**Comment by SSebastiano** [comment]
@SpinHalfLight @stloeffler @edocevoli @jacobgellman @u-fischer Yet the problem is visible: see follow-up [closed](https://github.com/MiKTeX/miktex/issues/1520)

**Comment by Ivan-Gudoshnikov** [comment]
I have just updated MikTeX to the most recent version. I am using the built-in TeXworks and the same problem apeared after the update.

**Comment by SSebastiano** [comment]
@SpinHalfLight @stloeffler @jacobgellman @Ivan-Gudoshnikov @u-fischer @edocevoli 
Thank you Ivan  for your feedback, but the problem is still real. There is a new version 0.7, but it is still in the experimental phase. I replaced the old executable texworks.exe in the MikTeX binary folder with the recent texworks from 01/10/2024, but the bad preview is visible for both TikZ libraries and any type of font. Best regards.
