### ISSUE TITLE
makeglossaries is failing

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#153]
After a recent update, I am receiving the following error message when attempting to make glossaries:

Process started: makeglossaries.exe "WorkingWithZoningOfficials"

makeglossaries.exe: The script engine could not be found. makeglossaries.exe: Data: scriptEngine="perl.exe"

Process exited with error(s)

The "makeglossaries.exe" file is located in the "C:\Program Files\MiKTeX 2.9\miktex\bin\x64" directory on my machine. This is on a Windows 10 PRO /amd64 machine.

**Comment by edocevoli** [comment]
Please make sure that `perl.exe` referenced in the `PATH` environment variable.

**Comment by BeerStud** [comment]
I can locate a "perltex.exe" but not a perl.exe file. Is this supposed to be installed by MiKTeX or some other package?

**Comment by IsabellLehmann** [comment]
> I can locate a "perltex.exe" but not a perl.exe file. Is this supposed to be installed by MiKTeX or some other package?

In case somebody is looking for this: perl must be downloaded separately (http://strawberryperl.com/, free version for Windows). The PATH variables should be added automatically during the installation. TexStudio must be restarted after installing perl. With Help -> Check LaTeX Installation, the path variables are printed in a .txt-file. Make sure that C:\Strawberry\perl\bin exists in the Path. Otherwise it has to be added to the windows path

**Comment by Parlazo** [comment]
> TexStudio must be restarted after installing perl

I did try every thing, and this was the simple solution. Strawberry is in the path after installing and TexStudio will see it after a simple restart... no need for bat files and strange stuff ;)
