### ISSUE TITLE
MiKTeX209-setup.dll missing after installation and package update

### ISSUE THREAD

**Issue by tbachcern** [MiKTeX/miktex#176]
I am unable to provide more information in #175, only collaborators can write. Please delete this issue here if this is the wrong way to provide more information.

Steps I did:

- Compile a .tex file with TexWorks (calls pdflatex)
- I got a log statement that I have to read
  `https://miktex.org/kb/mpm2016`
  Which says: You must update miktex. Option (1) failed. Option (2) says install current version of miktex, which I did. (Sorry for my bad wording when I tried to keep this short. I only followed the manual).
- I downloaded the current miktex installer
- I installed miktex with options: Din A4, Install always on the fly, default directory.
- After the installation finished, miktex requested to confirm package updates.
- I started the updates in the miktex console, the update process failed.
- After the failed update, miktex console (and any other miktex programs) do not run and show a `MiKTeX209-setup.dll missing` error
- I could not do anything anymore with my miktex installation and I was unable to repair it

I have left out my guess now why this happened and I focused on the step description as requested.

I do not care about the update issue, I am only concerned that an update abort leads to a missing `MiKTeX209-setup.dll`. This is most likely not trivial to solve for an average user. Therefore I expected this could be an interesting information. I am absolutely fine if this is not considered with reasons like this should not happen. But perhaps this problem was not considered so far.

I am happy to provide any more information if required. But in the end, I only want to draw attention to this possible state of the installation.

**Comment by edocevoli** [comment]
Thank you. So this is what happened:

- you have an outdated (pre 2016) MiKTeX installation which was never updated
- you are triggering the auto-installer (because a required file is missing)
- this fails with an error message (your MiKTeX installation is outdated)
- you download and run the latest installer; but you haven't removed the outdated MiKTeX installation

Please note that the installer does not upgrade an existing MiKTeX installation:
_**You have to remove the outdated MiKTeX installation before running the latest installer.**_

Remedy: remove your outdated MiKTeX installation then try again. If you still have issues: please attach the log files.
