### ISSUE TITLE
keeping user/admin updates in sync

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#262]
- [x] I have read the [MiKTeX Contributing Guidelines]

One of the most frequent source of problems (leading to questions on e.g. tex.sx) is that users of a multiuser installation don't update in both mode.  They get a fontspec update but not the needed l3kernel update, or latex but not babel, or complain that there are no updates but that package still doesn't have the new feature ....  I can't count how often I wrote in the last years "you must update miktex as user *and* as admin" or "did you update as user *and* as admin?" 

Could perhaps the console when used in user mode check also if admin updates exist and vice versa? Or at least ask the user after an update if he wants to check for updates in the other mode too?

**Comment by edocevoli** [comment]
MiKTeX Console (user mode) always checks for admin updates and present them in this way:

![miktex-console](https://user-images.githubusercontent.com/20090840/52532914-52a70800-2d2c-11e9-81a4-2bac54e63188.png)

**Comment by u-fischer** [comment]
While I have seen also users not doing admin updates (some times because of missing rights, sometimes because they probably never really check the update list ...), the main problem imho is the other way round: A lot users do the managment only in admin mode (as they think it is more powerful or similar reasons). And so packages which have been installed in the user tree through on-the-fly never get updated.

**Comment by moewew** [comment]
Do you think it would make sense to change the user-mode warning for admin-owned packages from a *negative* 'update not possible in user mode' to a *positive* 'update only possible in admin mode' or add something like 'update not possible in user mode: this package must be updated as admin'? Mentioning the admin bit may give users a better idea of what is required.

**Comment by edocevoli** [comment]
Yes, the text should be changed.

In addition, programs like `pdflatex` can issue a warning (or error) if the user/admin update status is not in sync:

```
C:\> pdflatex sample2e
pdflatex: warning: your MiKTeX installation is not up-to-date
pdflatex: warning: you should run 'mpm --update'
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6930 64-bit)
...
```

**Comment by moewew** [comment]
The warning is a nice idea, but if I've learned one thing it is that people don't read warnings. Many people use LaTeX via editors that parse TeX's output for them if the warning does not match their RegExps it will probably not be shown at all and even if it is shown it may be set aside as 'just a warning' and people might not even go back to it if everything is falling to pieces. On the other hand the warning may annoy people who consciously do not update their system (maybe because they are working on an important project right now).

**Comment by edocevoli** [comment]
MiKTeX Console now stays in user mode if there is a suspicion that user-mode packages are out of date:
![overdue](https://user-images.githubusercontent.com/20090840/54495473-670a9180-48e4-11e9-90f8-eff154b59ba5.png)

**Comment by edocevoli** [comment]
> A lot users do the managment only in admin mode (as they think it is more powerful or similar reasons). And so packages which have been installed in the user tree through on-the-fly never get updated.

I think this problem is now fixed:

1. A user with auto-installed packages opens MiKTeX Console
2. MiKTeX Console checks if admin/user mode updates are in sync
3. If a user mode update check is overdue, the alert message is shown and it's not immediately possible to switch to administrator mode

**Comment by thymaro** [comment]
> While I have seen also users not doing admin updates (some times because of missing rights, sometimes because they probably never really check the update list ...), the main problem imho is the other way round: A lot users do the managment only in admin mode (as they think it is more powerful or similar reasons). And so packages which have been installed in the user tree through on-the-fly never get updated.

Guilty as charged. I did *not* know the on-the-fly installations went to the user tree. I did everything in admin mode until now, since I installed MiKTeX in admin mode a few years ago and never cared to change to simple user mode.

> On the other hand the warning may annoy people who consciously do not update their system (maybe because they are working on an important project right now).

I wrote my thesis and ran package updates at least once to twice a week. I understand things could break, but I preferred doing regular updates and _if_ something broke, I would have a softer time (what's the opposite of a harder time, anyways?) fixing things, as issues would be easier to trace and fewer in numbers at a time. Updating after a few months on a whim could break a lot of things and bug hunting could take considerable time which was not budgeted for.

Anyways, thanks for this thread. I learned something new today.
