### ISSUE TITLE
copystart.exe and mpm_mfc.exe shortcuts not found

### ISSUE THREAD

**Issue by pzorba75** [MiKTeX/miktex#389]
Hi,
My PC works withs Windows 10, regularly updated and Miktex 2.9 for years. Today, i've run the Package Udpate manager (As Admin) tha tended normally. Since that operation, I've now a lot of problems. Latex documents can't be compiled successfully with TexMaker due to old or deprecated packages.
I'cannot launch Miktex Settings  and Miktex Update. The related window doesnt come and I'va a windows error telling copystart.exe and mpm_mfc.exe are not found.
As I'm not realy a geek, I'ask for assistance to fix my installation after this malicious update.
Regards 
Pierre

**Comment by edocevoli** [comment]
The mentioned executables are obsolete. They have been removed from the MiKTeX distribution.

If you have a problem with your MiKTeX setup, I would recommend that you describe your problem so that others are able to reproduce the problem. You should at least provide the log files.

Please read [this article](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md). Please open a new issue when ready.
