### ISSUE TITLE
MikTeX repositories list is now missing some repositority(s)

### ISSUE THREAD

**Issue by sbsheetz** [MiKTeX/miktex#40]
## My check list

- [X ] latest package versions are installed
- [ ] MiKTeX log files are attached
- [ ] the bug can be reproduced by anybody (necessary input files are attached)

## What I tried to do
Using the "Update (Admin)" utility, I selected "Let me choose a remote package repository" to select the repository I maintain, http://ctan.math.washington.edu. 

## What I expected to happen
I'm used to seeing quite a few more than 3 U.S. servers, mine included.   At the moment, there are only 3 U.S. hosts listed: ctan.math.illinois.edu, ctan.mirrors.hoobly.com, and mirrors.concertpass.com.   I've grown quite accustomed to selecting my own repository (ctan.math.washington.edu), but cannot.

## What happened instead
I select one of the listed U.S. hosts and the update succeeds successfully.   But selecting a repository other than mine is not optimal (given that my MikTeX installations are all on the same network as my repository server.

# Request for enhancment
Can the Remote Package Repository list be updated to include the rest of the CTAN mirrors (mine included) as it was previously?

**Comment by nicholaelaw** [comment]
MiKTeX pulls the list of available repositories from its own [source](https://miktex.org/pkg/repositories), instead of just fetching the CTAN repo list. Why this is the case, I don't know. Screening for non-functional repo?

My guess, regarding the missing repo problem, is that sometimes some repo would appear to be slightly behind on the synchronization so it was removed from MiKTeX repo list thereby not shown in the updater. There is no reason of removal shown anywhere, but you can see the warning in the log if you run the command:

```
mpm --admin --repository=<unlisted repo URL> --upgrade
```

Note that the repo URL should look like `<CTAN mirror URL>/systems/win32/miktex/tm/packages/`. 

Honestly I feel there's some weird thing going on here. Either the repo sync is really bad, or MiKTeX has bugs. Some facts:

- More often than not (I'd say 3/4) I could not find a single repo in China, while there are plenty mirrors listed on CTAN;
- I rarely encounter such problem with TeX Live distribution, with which I am considering to replace MiKTeX.

**Comment by edocevoli** [comment]
The downgraded repository list 12 days ago was due to a server process not running correctly. I have restarted the server process and the repository list now looks okay. Please feel free to open a new ticket if it happens again.
