### ISSUE TITLE
miktexsetup fails to call `initexmf --force --mklinks`

### ISSUE THREAD

**Issue by DrTwonky** [MiKTeX/miktex#443]
I noticed that since recently, MiKTeXsetup no longer creates files like `pdflatex.exe` and the like in a single-user-only setup. `initexmf.log` contains several FATALs, one about "Script configuration file not found", see attachments.

I installed MiKTeX using the command `miktexsetup.exe --local-package-repository=\\server\miktex  --modify-path=yes --package-set=essential --shared=no --use-registry=no install`.

[initexmf-report.txt](https://github.com/MiKTeX/miktex/files/3987874/initexmf-report.txt)
[initexmf.log](https://github.com/MiKTeX/miktex/files/3987861/initexmf.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/3987862/mpmcli.log)

However, calling `initexmf --mklinks` manually afterwards succeeds and creates the expected executables. 
Calling the other failed commands `initexmf --mkmaps --mklangs` and `initexmf --default-paper-size=A4` succeeds as well.

**Comment by albert-github** [comment]
I posted the question on texexchange (https://tex.stackexchange.com/questions/524088/installing-miktex-missing-executables-when-using-miktexsetup):

I'm installing MikTeX on appveyor CI, but I get the impression that the executables like bibtex and latex are not present anymore. The used procedure is:

- `appveyor-retry appveyor DownloadFile  https://miktex.org/download/win/miktexsetup-x64.zip`
- `7z e miktexsetup-x64.zip`
- `appveyor-retry miktexsetup.exe --local-package-repository=C:\miktex-repository --package-set=essential download`
- `miktexsetup.exe --local-package-repository=C:\miktex-repository --package-set=essential --shared install`

With where there was no result for these executables and I did a search over the complete C disk but couldn't find the executables either.

The impression is that the executables got missing on November 26, 2019 (but I'm not 100% sure about this).

And the comment received was:
> As a workaround, it should be possible to create the executables by running initexmf --admin --force --mklinks

I tried this but now I'm faced with:
```
Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:
  Script configuration file not found.
The log file hopefully contains the information to get MiKTeX going again:
  C:\ProgramData\MiKTeX\2.9\miktex\log\initexmf_admin.log
```

but the problem is that I cannot get the log file as the build terminates and the CI machine is gone for me.

**Comment by albert-github** [comment]
Most important question here is when will the problem (running of `initexmf` / providing the executables) be fixed and distributed so it can be used on e.g. appveyor CI?

**Comment by edocevoli** [comment]
I will fix it asap.

**Comment by edocevoli** [comment]
The package `miktex-misc` is now (again) an essential package. I think, this fixes this specific issue.

**Comment by albert-github** [comment]
I've just tested it with doxygen and the failing test (due to missing bibtex) now succeeds.
Thanks.
